version: '3.8'

services:

  app:
    container_name: quiz-app
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL= jdbc:postgresql://db:5432/quiz_db
    networks:
      - quiz-network

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: quiz_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: krapivko
    volumes:
      - ./db/init-scripts:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - quiz-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - quiz-network

networks:
  quiz-network:
    name: quiz-network
    driver: bridge

volumes:
  pgdata:
    name: pgdata
  pgadmin-data:
    name: pgadmin-data