version: '3.8'

services:

  app:
    image: arina343/quiz-app:latest
    container_name: quiz-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT = 8080
      - SPRING_DATASOURCE_URL = jdbc:postgresql://db:5432/quiz_db
    networks:
      - quiz-network

  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: quiz_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: krapivko
    volumes:
      - ./db/init-scripts:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - quiz-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - quiz-network
    restart: always

networks:
  quiz-network:
    name: quiz-network
    driver: bridge

volumes:
  pgdata:
    name: pgdata
  pgadmin-data:
    name: pgadmin-data